\c melanated_diamonds_dev

INSERT INTO businesses (name, address, contact_num, year_opened, is_online, is_store, img, category, website, description) VALUES
('DA SPOT', '445 ALBEE SQUARE WEST, BROOKLYN, NY 11201', '347-903-6729', 2017, true, true, 'https://cdn.shopify.com/s/files/1/2019/0047/files/Screenshot_2020-02-09-09-21-57_2_480x480.png?v=1586087614', 'fashion', 'https://daspotnyc.com/', 'Established in May 2017 by three independent Black creatives, Da Spot NYC ("DA SPOT") is a unique fashion boutique featuring 25+ creative brands by people of color. "DA SPOT" is also home to C.A.N.V.A.S Art Gallery, which features the works of local artists.'),
('Divine Express Catering', '992 Atlantic Ave, Brooklyn, NY 11238', '718-208-4488', 2005, true, true, 'https://divineflavoredcatering.com/wp-content/uploads/2021/09/logo_web.png', 'restaurant', 'https://dexpresscatering.com/', 'A family-owned and operated business specializing in Nigerian and African cuisine.'),
('Brooklyn Suya', '717 FRANKLIN AVE BROOKLYN, NY 11238', '718-513-0122', 2019, true, true, 'https://static01.nyt.com/images/2019/08/07/dining/01HUNGRY-SUYA-slide-GTRT/01HUNGRY-SUYA-slide-GTRT-articleLarge.jpg?quality=75&auto=webp&disable=upscale', 'restaurant', 'https://www.brooklynsuya.com/', 'Brooklyn Suya represents a merging of the Brooklyn + Nigerian culture centered around what we call a Suya Bowl. Each bowl starts with rice topped with your choice of grilled protein, sides, cucumber, tomatoes, signature house sauces, and of course, your choice of  mild, medium, spicy suya mix or, if your brave enough, atomic suya spice.'),
('MADE BY MALYIA', '', '347-258-3108', 2014, true, false, 'https://i.etsystatic.com/isla/967f19/35831789/isla_fullxfull.35831789_53ggpjmk.jpg?version=0', 'fashion', 'https://madebymalyia.com/', 'Each piece of jewelry from Made by Malyia is familiar yet unexpected, focusing on natural influences to give movement to the lines within the designs. The visionary behind the brand, Malyia, pulls inspiration from nature, travel, African culture, architecture and more to fuse each of these touch points into an innovative piece. All pieces are utterly versatile, using ethically sourced materials.'),
('Aseem Tri8e', '', '', 2020, true, false, 'https://cdn.shopify.com/s/files/1/0601/1299/4496/files/A2D350DA-F6A8-4ECB-912E-42242DAD4A7B_900x.jpg?v=1631554795', 'fashion', 'https://aseemtri8e.com/', 'Aseem means "unlimited/limitless/infinite" I feel it best describes the positive movement my friend Jace and I established. Sharing with others the power to unleash their LIMITLESS potential in all they seek to do. I was inspired by my family, unity with my soul tribe, and the divine forces of the universe to put together something special and meaningful that we all can enjoy!'),
('Wright Choice Creative Expressions and Event Planning', '', '205-649-0188', 2003, true, false, 'https://scontent-lga3-2.xx.fbcdn.net/v/t39.30808-6/241205945_4631953866847579_7088279414431485992_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=jLP7Gt72kKwAX818-Np&_nc_ht=scontent-lga3-2.xx&oh=00_AfDM9hQKagvteLLWfjsN8Oz199WWamcIg8K_rpyAGLh1TA&oe=6472E60F', 'fashion', 'https://www.facebook.com/wrightchoiceexpressions', 'Make the Wright Choice'),
('Kendras Boutique', '', '501-221-6776', 2012, true, false, 'https://cdn.knoji.com/images/logo/kendrasboutiquecom.jpg', 'beauty', 'https://kendrasboutique.com/', 'Kendras Boutique provides luxurious hair care products, including: platinum blonde closures, deep wave frontals, straight lace closures, and bundle deals.'),
('Mr. Blacks Boutique', '2210 NW 62nd st, Miami, Fl 33147', '305-635-8008', 1993, true, true, 'https://i.postimg.cc/zfdpBrHk/Mr-blacksboutique.jpg', 'fashion', 'https://mrblacksboutique.com/', 'Mr. Blacks Boutique is an established and trusted boutique based out of Miami, Florida. We have been in business for almost 30 years and pride ourselves in great customer service, quality products and the ability staying up-to-date with the latest trends.'),
('Sylvia''s', '328 Malcolm X Blvd New York, NY 10027', '212-996-0660', 1962, true, true, 'https://www.nycgo.com/images/videos/84544/sylvias-restaurant-thumbnail__large.jpg', 'restuarant', 'https://sylviasrestaurant.com/', 'Sylvia''s Restaurant, the “The Queen of Soul Food”, was founded by Sylvia Woods, in 1962. Established in the historic village of Harlem, Sylvia''s is a community favorite, known as the world''s kitchen. Serving authentic soul food for over 55 years, this icon remains a culinary must-visit for foodies.'),
('Harlem Haberdashery', '245 Lenox Avenue, New York, NY 10027', '646-707-0070', 2012, true, true, 'https://www.nycgo.com/images/venues/51441/harlem-haberdashery-manhattan-nyc-drielys-8244.jpg', 'fashion', 'https://www.harlemhaberdashery.com/', 'Harlem Haberdashery is a retail store and lifestyle brand that offers a curated selection of clothing, accessories, and gifts with a focus on celebrating African and African-American culture.'),
('Brooklyn Tea', '524 Nostrand Ave., Brooklyn, NY 11216', '347-240-4281', 2011, true, true, 'https://cdn.the-well.com/images/tl1ni0e8/production/6cdc8d06c2b22a90138d94d17eb970e037260da1-5472x3648.jpg?w=1280&h=720&fit=crop', 'restaurant', 'https://brooklyntea.com/', 'Brooklyn Tea is a tea shop and cafe that specializes in a wide variety of high-quality loose-leaf teas. They also offer tea accessories, pastries, and a cozy space for tea lovers to relax and enjoy'),
('The Lit. Bar', '131 Alexander Avenue, Bronx, NY 10454', '(347) 955-3610', 2019, true, true, 'https://media.shelf-awareness.com/theshelf/2019_Edit_Content/lit_bar_IG_040219.JPG', 'social', 'http://www.thelitbar.com/', 'The Lit. Bar is a bookstore and wine bar located in the South Bronx. They offer a wide selection of books, including a curated collection of works by diverse authors. Customers can browse books while enjoying a glass of wine or attending literary events'),
('Bed-Vyne Brew', '370 Tompkins Avenue, Brooklyn, NY 11216', '347-915-1080', 2013, true, true, 'https://www.vmcdn.ca/f/files/bkreader/import/2019_08_IMG_8595.jpg;w=960', 'restaurant', 'https://brew.bed-vyne.com/', 'Bed-Vyne Brew is a craft beer and wine shop in Brooklyn. They specialize in offering a diverse selection of beers, wines, and spirits, with a focus on supporting local and minority-owned brands.'),
('Negril Village', '70 W 3rd Street, New York, NY 10012', '212-477-2804', 1997, true, true, 'https://islandgirlintransit.com/wp-content/uploads/2016/09/IMG_6598-e1473260371181.jpg', 'restaurant', 'https://www.negrilvillage.com/', 'Negril Village is a vibrant Caribbean restaurant that serves delicious dishes inspired by the flavors of Jamaica. They provide a lively atmosphere, live music, and a range of tropical cocktails.'),
('The Brownstone Woman', '24 E 125th Street, New York, NY 10035', '646-918-6782', 2010, true, true, 'https://s3-media0.fl.yelpcdn.com/bphoto/jUlEfp5pouvvGb4koKSAbw/l.jpg', 'fashion', 'https://www.thebrownstonewoman.com/', 'The Brownstone Woman is a boutique that offers a curated collection of clothing, accessories, and jewelry for women. They specialize in unique and stylish pieces that reflect individuality and cultural heritage.'),
('Brooklyn Bell', '843 Classon Avenue, Brooklyn, NY 11238', '347-915-3401', 2011, true, true, 'http://www.brooklynbell.com/wp-content/uploads/2017/03/ron.jpg', 'restaurant', 'http://www.brooklynbell.com/', 'Brooklyn Bell is an artisanal ice cream shop that creates handcrafted, small-batch ice creams using locally sourced ingredients. They offer a variety of unique flavors and also provide vegan and dairy-free options.'),
('Nicholas Brooklyn', '1396 Fulton Street, Brooklyn, NY 11216', '(718) 858-4400', 1974, true, true, 'https://nicholasbrooklyn.com/wp-content/uploads/2020/12/IMG_6847-x2.png', 'fashion', 'https://nicholasbrooklyn.com/', 'Nicholas Brooklyn is a clothing store that specializes in Afrocentric and contemporary fashion for men, women, and children. They offer a wide range of clothing, accessories, and lifestyle products.'),
('Sol Cacao', '780E 133rd, Bronx, NY, 10454', '929-294-5111', 2017, true, true, 'https://scontent-lga3-2.xx.fbcdn.net/v/t1.6435-9/118126786_2583818475264123_8380627724177145213_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=9267fe&_nc_ohc=_4r_d_jn6cIAX8x9t0e&_nc_ht=scontent-lga3-2.xx&oh=00_AfB-iBycy_kqr7u2ra6DC8Opt7GJuDChVtIWwFbVQg12mw&oe=6494A314', 'restaurant', 'https://www.solcacao.com/', 'Sol Cacao is a bean-to-bar chocolate company that produces high-quality, single-origin chocolates. They source their cacao beans directly from farmers and focus on maintaining a sustainable and ethical supply chain.'),
('Hue-Man Bookstore & Cafe', '2319 Frederick Douglass Boulevard, New York, NY 10027', '212-665-7400', 2002, true, true, 'https://observer.com/wp-content/uploads/sites/2/2012/07/hue-man_v1_460x285.jpeg?quality=80&strip', 'social', 'https://www.huemanbooks.com/', 'Hue-Man Bookstore & Cafe is an independent bookstore that specializes in books written by African-American authors. They also have a café area where customers can enjoy coffee, pastries, and conversation.'),
('The Crabby Shack', '613 Franklin Avenue, Brooklyn, NY 11238', '718-484-1507', 2012, true, true, 'https://i-am-black-business-prod.nyc3.digitaloceanspaces.com/business/the-crabby-shack-in-crown-heights.jpg', 'restaurant', 'https://thecrabbyshack.com/', 'The Crabby Shack is a seafood restaurant that specializes in serving delicious crab dishes. They source their seafood from sustainable fisheries and offer a variety of tasty options for seafood lovers.'),
('The Brownstone Jazz', '107 Macon Street, Brooklyn, NY 11216', '917-704-9237', 2009, true, true, 'https://d10j3mvrs1suex.cloudfront.net/s:bzglfiles/u/222548/12aeeb8b625d1d3e68f0625ed0c2705ac17cf376/original/italy-sunset-beach.jpg/!!/b%3AW1sicmVzaXplIiwxODAwXSxbIm1heCJdLFsid2UiXV0%3D/meta%3AeyJzcmNCdWNrZXQiOiJiemdsZmlsZXMifQ%3D%3D.jpg', 'social', 'https://brownstonejazz.business.site/', 'The Brownstone Jazz is a cozy jazz club located in Brooklyn. They feature live jazz performances by talented musicians, creating a welcoming space for jazz enthusiasts to enjoy the music.'),
('Taste Of Heaven', '251 Jackson St, Brooklyn, NY 11211', '718-576-3146', 2015, true, true, 'https://i0.wp.com/greenpointers.com/app/uploads/2021/12/taste-of-heaven-by-julia-moak-MelTony2.jpg?resize=780%2C1040&ssl=1', 'restaurant', 'http://www.tasteofheavenbk.com/', 'Taste of Heaven was started with love and is reflected in the food we serve. We pride ourselves on our tasty Soul Food Cuisine at the right price. We love it so much we named the restaurant after our daughter, Heaven.'),
('Calabar Imports', '2504 Frederick Douglass Boulevard, New York, NY 10030', '212-234-3045', 2002, true, true, 'https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/239913291_4174932212634093_6074914435085993860_n.jpg?_nc_cat=110&ccb=1-7&_nc_sid=8bfeb9&_nc_ohc=AVEMwU2A6psAX96c4ZB&_nc_ht=scontent-lga3-1.xx&oh=00_AfBPZCMoPXF0qpSJA7lb1XxiYSvf_txxze-KTCHFx0CdsA&oe=64722A14', 'fashion', 'http://calabar-imports.com/', 'Calabar Imports is a boutique that features clothing, accessories, and home decor inspired by African and Caribbean designs. They showcase unique and vibrant pieces that celebrate cultural heritage.'),
('Sisters Caribbean Cuisine', '47 E 124th Street, New York, NY 10035', '212-410-3000', 1994, true, true, 'https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/277792555_399386512148994_7076041845323344779_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=niby_fN9XnYAX8GpfVE&_nc_ht=scontent-lga3-1.xx&oh=00_AfC40T2RBJmr2ffrRNIZJpxdjP7fjViAKtwQXKy0HKdQMg&oe=6471EA43', 'restaurant', 'https://www.sisterscuisineharlem.com/', 'Sisters Caribbean Cuisine is a family-owned restaurant that offers a taste of Caribbean flavors. They serve traditional dishes from various Caribbean islands, providing a culinary journey for customers.'),
('T.Cox Studios', '247 Troy Ave, Brooklyn, NY 11213', '917-310-8123', 2015, true, true, 'https://images.squarespace-cdn.com/content/v1/56493090e4b0f54883cd2be1/1475890284947-PZKSFDBJFVWBQOPMXD8U/image-asset.jpeg?format=1500w', 'barber shop', 'https://tcoxstudios.com/', 'T. Cox Studios is a one of a kind Barbershop, we are big on quality service and confidentiality. The core value of our brand is acceptance of all genders and race. We create a bond with our clients, while giving them a fresh new feel with a boost of confidence. When it comes to our services its more than just a new look, but an experience.'),
('Levels Barbershop', '425 W 125th St #1, New York, NY 10027', '212-663-6144', 1996, true, true, 'https://freshnyc.com/sites/default/files/field/image/barbers_levels.jpg', 'barber shop', 'https://levelsbarbershop.com/', 'Levels'' is a multifaceted barbershop that specializes in the styling, grooming and overall hair care for men, women and children. Our services include the trimming and acute styling of natural hair maintenance and grooming we also offer additional specialized services such as detailed hair braiding and straight razor shaves and trims.'),
('Camera Ready Kutz, Inc.', '73 Utica Ave, Brooklyn, NY 11213', '347-349-5889', 2007, true, true, 'https://images.squarespace-cdn.com/content/v1/631571e96ddd1917e764bb71/c1091feb-62ae-4b39-baf6-7e36e7b04fa3/IMG_8684.PNG?format=1500w', 'barber shop', 'https://www.camerareadykutz.com/', 'Camera Ready Kutz, Inc. is a Black Owned•Female Owned•LGBTQIA+ Owned barbershop geared towards, but not exclusive to the LGBTQIA+ community. CRKutz provides a Brave Space where people of all sexual orientations and gender expressions can comfortably get groomed without worrying about being refused service, hearing derogatory comments or feeling as though they have to act in an "acceptable" manner for the sake of personal safety.'),
('Adrian Fanus Grooming', '651 Bushwick Ave, Brooklyn, NY 11221', '347-533-8827', 2009, true, true, 'https://www.loverlysheridan.com/wp-content/uploads/2012/09/af-grooming1.jpg', 'barber shop', 'https://afgrooming.com/', 'AFG presents environment that is almost an oasis in the midst of a desert. Here you can retreat into a space of luxury and comfort. Upon entering you will be presented with a courtesy beverage ranging from champagne, to wine, seasonal drinks, to various teas, or a bevy of juices. As you receive your select beverage you will be escorted to our plush waiting area, outfit with comfortable leather furniture, a flat screen TV, cable, a chess set, and a wide array of books and magazines to entertain you until the start of your appointment.'),

('Troy''s Barber Shop', '820 Wyckoff Ave, Brooklyn, NY 11237', '718-386-8645', 2003, true, true, 'https://dailybarber.com/wp-content/uploads/Troys-Barber-Shop-Brooklyn-logo.png', 'barber shop', 'https://troysbarbershop.square.site/', 'Professional service.'),
('Brooklyn Tonsorial', '369A Nostrand Ave., Brooklyn, NY 11216', '917-966-5622', 2015, true, true, 'https://www.brooklyntonsorial.com/uploads/1/1/1/0/111009363/published/brooklyn-tonsorial-logo_1.png?1510280153', 'barber shop', 'https://www.brooklyntonsorial.com/', 'Brooklyn Tonsorial is a full-service Barbershop catering to people with all hair types, located in Bed-Stuy, Brooklyn.'),
('Denny Moe''s Superstar Barbershop', '2496 Frederick Douglass Boulevard New York, NY 10030', '212-690-0015', 1983, true, true, 'https://fastly.4sqi.net/img/general/600x600/28517_CXv5WT_7Z_cNpOWtiRByAmFqo7dzYktIe6rFPu-M63Q.jpg', 'barber shop', 'https://dennymoe.com/', 'Denny Moe''s Superstar Barbershop is fully staffed with master barbers ready to provide tailored services that meet your needs. Each Client that walks through our doors has a unique sense of taste. We aim to capture this individuality by providing premium services suited to each person''s style and personality. Our barbers understand the differences between each client and value the trust confided in us when they sit in our chairs. We aim to please.'),
('Black Success Barber Shop', '729 Pennsylvania Avenue Brooklyn, NY 11207', '718-257-2919', 2005, true, true, 'https://lh3.googleusercontent.com/p/AF1QipNYDichOZE34Txr-SyJFNbcWmz3Tn_9zkJKtMCf=w768-h768-n-o-k-v1', 'barber shop', 'https://black-success-barber-shop.business.site/', 'Black Success Barber Shop is an old school neighborhood barber shop. The barbers are professional, the environment is homey, and multigenerational. You are surrounded by images from African American History. The price point is excellent.'),
('Carver Federal Savings Bank', '1392 Fulton St, Brooklyn, NY 11216', '718-230-2900', 1948, true, true, 'https://media.glassdoor.com/l/03/a8/bb/4b/president-and-amp-ceo-michael-pugh.jpg', 'bank', 'https://www.carverbank.com/', 'Carver is one of the largest African American operated banks in the United States (NASDAQ:CARV).  Headquartered in Harlem, Carver has seven full-service branches and 24/7 ATM Centers located in low- to moderate- income neighborhoods.'),
('OneUnited Bank', '648 Warren St, Dorchester, MA 02121', '617-457-4400', 1968, true, true, 'https://www.oneunited.com/core/content/uploads/2021/08/BankBlackAdvantagetransparentlogo.png', 'bank', 'https://www.oneunited.com/', 'OneUnited Bank is the largest black-owned bank in the country. They provide a full range of banking products and services, including checking and savings accounts, home loans, business banking, and community development initiatives.'),
('First Independence Bank', '7310 Woodward Ave #101, Detroit, MI 48202', '313-256-8400', 1970, true, true, 'https://cdn.dbusiness.com/wp-content/uploads/sites/33/2023/03/FirstIndependence800.jpg', 'bank', 'https://www.firstindependence.com/', 'First Independence Bank is a black-owned community bank that provides a comprehensive range of financial services, including personal and business banking, loans, mortgages, and investment options.');

INSERT INTO user_profile (first_name,last_name,username,email,password) VALUES
('first','last','username','email','pw');