\c melanated_diamonds_dev

INSERT INTO businesses (name, address, contact_num, year_opened, is_online, is_store, img, category, website, description) VALUES
('DA SPOT', '445 ALBEE SQUARE WEST, BROOKLYN, NY 11201', '347-903-6729', 2017, true, true, 'https://cdn.shopify.com/s/files/1/2019/0047/files/Screenshot_2020-02-09-09-21-57_2_480x480.png?v=1586087614', 'fashion', 'https://daspotnyc.com/', 'Established in May 2017 by three independent Black creatives, Da Spot NYC ("DA SPOT") is a unique fashion boutique featuring 25+ creative brands by people of color. "DA SPOT" is also home to C.A.N.V.A.S Art Gallery, which features the works of local artists.'),
('Divine Express Catering', '992 Atlantic Ave, Brooklyn, NY 11238', '718-208-4488', 2005, true, true, 'https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/302099304_979039209714265_6756093443916564037_n.png?_nc_cat=110&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=1IIGW4beaWQAX8cLx5h&_nc_ht=scontent-lga3-1.xx&oh=00_AfDgsW-hfZ3Nk8oBUA6EjRdLPWt31Zv-j9lXUaKknzPF-Q&oe=645CB4B3', 'restaurant', 'https://dexpresscatering.com/', 'A family-owned and operated business specializing in Nigerian and African cuisine.'),
('Brooklyn Suya', '717 FRANKLIN AVE BROOKLYN, NY 11238', '718-513-0122', 2019, true, true, 'https://static01.nyt.com/images/2019/08/07/dining/01HUNGRY-SUYA-slide-GTRT/01HUNGRY-SUYA-slide-GTRT-articleLarge.jpg?quality=75&auto=webp&disable=upscale', 'restaurant', 'https://www.brooklynsuya.com/', 'Brooklyn Suya represents a merging of the Brooklyn + Nigerian culture centered around what we call a Suya Bowl. Each bowl starts with rice topped with your choice of grilled protein, sides, cucumber, tomatoes, signature house sauces, and of course, your choice of  mild, medium, spicy suya mix or, if your brave enough, atomic suya spice.'),
('MADE BY MALYIA', '', '347-258-3108', 2014, true, false, 'https://scontent-lga3-1.xx.fbcdn.net/v/t39.30808-6/317998489_842782797036018_8852338841211053298_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=730e14&_nc_ohc=h5kZDnCEsZ0AX9_wLCa&_nc_ht=scontent-lga3-1.xx&oh=00_AfDgbGkw0lIYnutLvGMwMhipCu5uJceVKBJqyRPFnQzqrw&oe=645CD7CD', 'fashion', 'https://madebymalyia.com/', 'Each piece of jewelry from Made by Malyia is familiar yet unexpected, focusing on natural influences to give movement to the lines within the designs. The visionary behind the brand, Malyia, pulls inspiration from nature, travel, African culture, architecture and more to fuse each of these touch points into an innovative piece. All pieces are utterly versatile, using ethically sourced materials.'),
('Aseem Tri8e', '', '', 2020, true, false, 'https://scontent-lga3-2.xx.fbcdn.net/v/t39.30808-6/277001484_108116935180554_6280968332157799816_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=r5K4WyKhucgAX-6lLq6&_nc_ht=scontent-lga3-2.xx&oh=00_AfC8meXY-M8pUcT-D5k3BMohHxqC55W4kYQcO-R4XioJdw&oe=645C02B7', 'fashion', 'https://aseemtri8e.com/', 'Aseem means "unlimited/limitless/infinite" I feel it best describes the positive movement my friend Jace and I established. Sharing with others the power to unleash their LIMITLESS potential in all they seek to do. I was inspired by my family, unity with my soul tribe, and the divine forces of the universe to put together something special and meaningful that we all can enjoy!'),
('Wright Choice Creative Expressions and Event Planning', '', '205-649-0188', 2003, true, false, 'https://scontent-lga3-2.xx.fbcdn.net/v/t39.30808-6/241205945_4631953866847579_7088279414431485992_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=6WJ2feGU0FYAX-aHlHO&_nc_ht=scontent-lga3-2.xx&oh=00_AfC9WTeJnoAHP1W8IeU0OAkQ_2JIQ_vNL5hDz4GBRt5MmQ&oe=645D254F', 'fashion', 'https://www.facebook.com/wrightchoiceexpressions', 'Make the Wright Choice'),
('Kendras Boutique', '', '501-221-6776', 2012, true, false, 'https://cdn.knoji.com/images/logo/kendrasboutiquecom.jpg', 'beauty', 'https://kendrasboutique.com/', 'Kendras Boutique provides luxurious hair care products, including: platinum blonde closures, deep wave frontals, straight lace closures, and bundle deals.'),
('Mr. Blacks Boutique', '2210 NW 62nd st, Miami, Fl 33147', '305-635-8008', 1993, true, true, 'https://i.postimg.cc/zfdpBrHk/Mr-blacksboutique.jpg', 'fashion', 'https://mrblacksboutique.com/', 'Mr. Blacks Boutique is an established and trusted boutique based out of Miami, Florida. We have been in business for almost 30 years and pride ourselves in great customer service, quality products and the ability staying up-to-date with the latest trends.'),
('Sylvia"s', '328 Malcolm X Blvd New York, NY 10027', '212-996-0660', 1962, true, true, 'https://www.nycgo.com/images/videos/84544/sylvias-restaurant-thumbnail__large.jpg', 'restuarant' 'https://sylviasrestaurant.com/', 'Sylvia`s Restaurant, the “The Queen of Soul Food”, was founded by Sylvia Woods, in 1962. Established in the historic village of Harlem, Sylvia`s is a community favorite, known as the world`s kitchen. Serving authentic soul food for over 55 years, this icon remains a culinary must-visit for foodies.'),
('Harlem Haberdashery', '245 Lenox Avenue, New York, NY 10027', '646-707-0070', 2012, true, true, 'https://www.nycgo.com/images/venues/51441/harlem-haberdashery-manhattan-nyc-drielys-8244.jpg', 'fashion', 'https://www.harlemhaberdashery.com/', 'Harlem Haberdashery is a retail store and lifestyle brand that offers a curated selection of clothing, accessories, and gifts with a focus on celebrating African and African-American culture.'),
('Brooklyn Tea', '524 Nostrand Ave., Brooklyn, NY 11216', '347-240-4281', 2011, true, true, 'https://cdn.the-well.com/images/tl1ni0e8/production/6cdc8d06c2b22a90138d94d17eb970e037260da1-5472x3648.jpg?w=1280&h=720&fit=crop', 'restaurant', 'https://brooklyntea.com/', 'Brooklyn Tea is a tea shop and cafe that specializes in a wide variety of high-quality loose-leaf teas. They also offer tea accessories, pastries, and a cozy space for tea lovers to relax and enjoy'),
('The Lit. Bar', '131 Alexander Avenue, Bronx, NY 10454', '(347) 955-3610', 2019, true, true, 'https://media.shelf-awareness.com/theshelf/2019_Edit_Content/lit_bar_IG_040219.JPG', 'social', 'http://www.thelitbar.com/', 'The Lit. Bar is a bookstore and wine bar located in the South Bronx. They offer a wide selection of books, including a curated collection of works by diverse authors. Customers can browse books while enjoying a glass of wine or attending literary events'),
('Bed-Vyne Brew', '370 Tompkins Avenue, Brooklyn, NY 11216', '347-915-1080', 2013, true, true, 'https://www.vmcdn.ca/f/files/bkreader/import/2019_08_IMG_8595.jpg;w=960', 'restaurant', 'https://brew.bed-vyne.com/', 'Bed-Vyne Brew is a craft beer and wine shop in Brooklyn. They specialize in offering a diverse selection of beers, wines, and spirits, with a focus on supporting local and minority-owned brands.'),
('Negril Village', '70 W 3rd Street, New York, NY 10012', '212-477-2804', 1997, false, true, 'image', 'restaurant', 'website', 'Negril Village is a vibrant Caribbean restaurant that serves delicious dishes inspired by the flavors of Jamaica. They provide a lively atmosphere, live music, and a range of tropical cocktails.'),
('The Brownstone', '24 E 125th Street, New York, NY 10035', '646-918-6782', 2010, true, true, 'image', 'fashion', 'website', 'The Brownstone is a boutique that offers a curated collection of clothing, accessories, and jewelry for women. They specialize in unique and stylish pieces that reflect individuality and cultural heritage.'),
('Brooklyn Bell', '843 Classon Avenue, Brooklyn, NY 11238', '347-915-3401', 2011, true, true, 'iamge', 'restaurant', 'website', 'Brooklyn Bell is an artisanal ice cream shop that creates handcrafted, small-batch ice creams using locally sourced ingredients. They offer a variety of unique flavors and also provide vegan and dairy-free options.'),
('Nicholas Brooklyn', '1396 Fulton Street, Brooklyn, NY 11216', '(718) 858-4400', 1982, true, true, 'image', 'fashion', 'website', 'Nicholas Brooklyn is a clothing store that specializes in Afrocentric and contemporary fashion for men, women, and children. They offer a wide range of clothing, accessories, and lifestyle products.'),
('Effie`s Kitchen', '259 Utica Avenue, Brooklyn, NY 11213', '', 2011, false, true, 'image', 'restaurant', 'website', 'Effie`s Kitchen is a family-owned restaurant that serves delicious and authentic Caribbean cuisine. They are known for their flavorful dishes, warm hospitality, and welcoming atmosphere.'),
('Sol Cacao', '104 Meserole Street, Brooklyn, NY 11206', '347-384-2919', 2015, true, true, 'image', 'restaurant', 'website', 'Sol Cacao is a bean-to-bar chocolate company that produces high-quality, single-origin chocolates. They source their cacao beans directly from farmers and focus on maintaining a sustainable and ethical supply chain.'),
('Hue-Man Bookstore & Cafe', '2319 Frederick Douglass Boulevard, New York, NY 10027', '212-665-7400', 2002, true, true, 'image', 'social', 'website', 'Hue-Man Bookstore & Cafe is an independent bookstore that specializes in books written by African-American authors. They also have a café area where customers can enjoy coffee, pastries, and conversation.'),
('The Crabby Shack', '613 Franklin Avenue, Brooklyn, NY 11238', '718-484-1507', 2012, true, true, 'image', 'restaurant', 'website', 'The Crabby Shack is a seafood restaurant that specializes in serving delicious crab dishes. They source their seafood from sustainable fisheries and offer a variety of tasty options for seafood lovers.'),
('The Brownstone Jazz', '107 Macon Street, Brooklyn, NY 11216', '917-704-9237', 2009, false, true, 'image', 'social', 'website', 'The Brownstone Jazz is a cozy jazz club located in Brooklyn. They feature live jazz performances by talented musicians, creating a welcoming space for jazz enthusiasts to enjoy the music.'),
('Heaven`s Taste', '721 Nostrand Avenue, Brooklyn, NY 11216', '347) 787-7521', 2016, false, true, 'image', 'restaurant', 'website', 'Heaven`s Taste is a soul food restaurant that offers a variety of mouthwatering dishes. From fried chicken and macaroni and cheese to collard greens and peach cobbler, they provide classic comfort food flavors.'),
('Calabar Imports', '2504 Frederick Douglass Boulevard, New York, NY 10030', '212-234-3045', 2002, true, true, 'image', 'fashion', 'website', 'Calabar Imports is a boutique that features clothing, accessories, and home decor inspired by African and Caribbean designs. They showcase unique and vibrant pieces that celebrate cultural heritage.'),
('The Crabby Pig', '2525 7th Avenue, New York, NY 10039', '212-694-4664', 2018, true, true, 'image', 'restaurant', 'website', 'The Crabby Pig is a soul food restaurant that serves a fusion of Southern and Caribbean flavors. Their menu includes delectable dishes like jerk chicken, oxtails, and seafood gumbo.'),
('Sisters Caribbean Cuisine', '47 E 124th Street, New York, NY 10035', '212-410-3000', 1994, true, true, 'image', 'restaurant', 'website', 'Sisters Caribbean Cuisine is a family-owned restaurant that offers a taste of Caribbean flavors. They serve traditional dishes from various Caribbean islands, providing a culinary journey for customers.');

INSERT INTO user_profile (first_name,last_name,username,email,password) VALUES
('first','last','username','email','pw');